/* Miss Sophie AI Engine */
const SOPHIE_CONFIG={apiKey:'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',model:'claude-sonnet-4-6',apiUrl:'https://api.anthropic.com/v1/messages'};
const Progress={key:'sophie_progress',load(){try{return JSON.parse(localStorage.getItem(this.key))||{};}catch{return{};}},save(d){localStorage.setItem(this.key,JSON.stringify(d));},getChild(n){const d=this.load();if(!d[n])d[n]={stars:0,maths:0,handwriting:0,reading:0,spelling:0,level:1};return d[n];},addStars(n,x=1){const d=this.load();const c=this.getChild(n);c.stars+=x;if(c.stars%10===0)c.level=Math.min(c.level+1,5);d[n]=c;this.save(d);return c.stars;},addSubjectProgress(n,s,x=1){const d=this.load();const c=this.getChild(n);c[s]=(c[s]||0)+x;d[n]=c;this.save(d);}};
const PHONETIC_NAMES={'Milla':'Millah'};
const Voice={speaking:false,_voice:null,_ready:false,init(){if(this._ready)return;const load=()=>{const voices=speechSynthesis.getVoices();if(!voices.length)return;const priority=['Samantha','Karen','Victoria','Moira','Tessa','Google UK English Female','Microsoft Zira','Microsoft Susan','Fiona'];let found=null;for(const name of priority){found=voices.find(v=>v.name.includes(name));if(found)break;}if(!found)found=voices.find(v=>v.lang.startsWith('en')&&/female|woman|girl/i.test(v.name));if(!found)found=voices.find(v=>v.lang==='en-AU'||v.lang==='en-GB');if(!found)found=voices.find(v=>v.lang.startsWith('en'));this._voice=found||null;this._ready=true;};if(speechSynthesis.getVoices().length){load();}else{speechSynthesis.addEventListener('voiceschanged',load,{once:true});}},prep(text){let t=text.replace(/[*_~`#]/g,'');for(const[name,ph]of Object.entries(PHONETIC_NAMES)){t=t.replace(new RegExp('\b'+name+'\b','g'),ph);}t=t.replace(/([.!?])s+/g,'$1  ');t=t.replace(/,s+/g,',  ');t=t.replace(/[.][.][.]/g,',  ');return t.trim();},speak(text,onEnd){if(!window.speechSynthesis){if(onEnd)onEnd();return;}if(!this._ready)this.init();const clean=this.prep(text);const utt=new SpeechSynthesisUtterance(clean);utt.rate=0.82;utt.pitch=1.08;utt.volume=1;if(this._voice)utt.voice=this._voice;utt.onend=()=>{this.speaking=false;if(onEnd)onEnd();};utt.onerror=()=>{this.speaking=false;if(onEnd)onEnd();};this.speaking=true;speechSynthesis.cancel();setTimeout(()=>speechSynthesis.speak(utt),100);},stop(){speechSynthesis.cancel();this.speaking=false;}};
document.addEventListener('click',()=>{speechSynthesis.getVoices();Voice.init();},{once:true});
const Listen={recognition:null,active:false,init(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return false;this.recognition=new SR();this.recognition.continuous=false;this.recognition.interimResults=false;this.recognition.lang='en-AU';return true;},start(onResult,onEnd){if(!this.recognition&&!this.init()){onEnd&&onEnd('');return;}this.active=true;this.recognition.onresult=e=>{onResult(e.results[0][0].transcript);};this.recognition.onend=()=>{this.active=false;onEnd&&onEnd();};this.recognition.onerror=()=>{this.active=false;onEnd&&onEnd('');};try{this.recognition.start();}catch(e){}},stop(){this.active=false;try{this.recognition&&this.recognition.stop();}catch(e){}}};
const Sophie={childName:'Milla',childAge:6,subject:'general',systemPrompt(){return `You are Miss Sophie, a warm loving teacher talking out loud to ${this.childName} who is ${this.childAge} years old. You are teaching ${this.subject}. Speak in a gentle, natural, conversational way as if sitting next to them. Always say their name warmly. Keep every reply to 1 or 2 short simple sentences. Never use lists, bullet points, or markdown. Use natural speech with commas for pauses. If they tell a joke, laugh with a warm ha ha and say something sweet. Sound like a kind real person, not a robot.`;},async ask(msg,ctx=''){const prompt=ctx?`Context: ${ctx}\nChild said: "${msg}"`:msg;try{const res=await fetch(SOPHIE_CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','x-api-key':SOPHIE_CONFIG.apiKey,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:SOPHIE_CONFIG.model,max_tokens:120,system:this.systemPrompt(),messages:[{role:'user',content:prompt}]})});const data=await res.json();return data?.content?.[0]?.text||`Great effort ${this.childName}!`;}catch(e){return `Great effort ${this.childName}! Keep going!`;}},praise(n){const p=[`Oh wow, great job ${n}!`,`You are so clever ${n}, I am so proud of you!`,`Woohoo! That is right ${n}!`,`Brilliant work ${n}, you are doing amazing!`,`Yes! You got it ${n}! I knew you could do it!`,`Super star ${n}, well done!`];return p[Math.floor(Math.random()*p.length)];},encourage(n){const p=[`Almost ${n}, have another try, you are so close!`,`Oops, that is okay ${n}, let us try again together!`,`Not quite ${n}, but I believe in you!`,`Keep going ${n}, you are doing really well!`];return p[Math.floor(Math.random()*p.length)];}};
function launchConfetti(count=40){const colors=['#FF6EB4','#9B59B6','#FFD700','#74B9FF','#55EFC4'];for(let i=0;i<count;i++){const el=document.createElement('div');el.className='confetti-piece';el.style.left=Math.random()*100+'vw';el.style.background=colors[Math.floor(Math.random()*colors.length)];el.style.animationDuration=(1.5+Math.random()*2)+'s';el.style.animationDelay=(Math.random()*.8)+'s';document.body.appendChild(el);el.addEventListener('animationend',()=>el.remove());}}
function initStars(count=18){const wrap=document.querySelector('.stars');if(!wrap)return;for(let i=0;i<count;i++){const s=document.createElement('div');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=(Math.random()*3)+'s';s.style.animationDuration=(2+Math.random()*2)+'s';s.style.width=s.style.height=(6+Math.random()*10)+'px';wrap.appendChild(s);}}
function getCurrentChild(){return sessionStorage.getItem('sophie_child')||'Milla';}
function getCurrentAge(){return parseInt(sessionStorage.getItem('sophie_age')||'6');}
function setCurrentChild(name,age=6){sessionStorage.setItem('sophie_child',name);sessionStorage.setItem('sophie_age',age);Sophie.childName=name;Sophie.childAge=age;}
function updateScoreDisplay(){const child=getCurrentChild();const data=Progress.getChild(child);const el=document.getElementById('stars-count');if(el)el.textContent=data.stars;}
