/* Miss Sophie AI Engine */
const SOPHIE_CONFIG={apiKey:'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',model:'claude-sonnet-4-6',apiUrl:'https://api.anthropic.com/v1/messaghes'};
const Progress={key:'sophie_progress',load(){try{return JSON.parse(localStorage.getItem(this.key))||{};}catch{return{};}},save(d){localStorage.setItem(this.key,JSON.stringify(d));},getChild(n){const d=this.load();if(!d[n])d[n]={stars:0,maths:0,handwriting:0,reading:0,spelling:0,level:1};return d[n];},addStars(n,x=1){const d=this.load();const c=this.getChild(n);c.stars+=x;if(c.stars%10===0)c.level=Math.min(c.level+1,5);d[n]=c;this.save(d);return c.stars;},addSubjectProgress(n,s,x=1){const d=this.load();const c=this.getChild(n);c[s]=(c[s]||0)+x;d[n]=c;this.save(d);}};
const Voice={speaking:false,speak(text,onEnd){if(!window.speechSynthesis){if(onEnd)onEnd();return;}text=text.replace(/[*_~`#]/g,'');const utt=new SpeechSynthesisUtterance(text);utt.rate=0.88;utt.pitch=1.2;utt.volume=1;const voices=speechSynthesis.getVoices();const preferred=voices.find(v=>/samantha|karen|victoria|zira|female|woman/i.test(v.name))||voices.find(v=>v.lang.startsWith('en'))||voices[0];if(preferred)utt.voice=preferred;utt.onend=()=>{this.speaking=false;if(onEnd)onEnd();};utt.onerror=()=>{this.speaking=false;if(onEnd)onEnd();};this.speaking=true;speechSynthesis.cancel();speechSynthesis.speak(utt);},stop(){speechSynthesis.cancel();this.speaking=false;}};
document.addEventListener('click',()=>speechSynthesis.getVoices(),{once:true});
const Listen={recognition:null,active:false,init(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return false;this.recognition=new SR();this.recognition.continuous=false;this.recognition.interimResults=false;this.recognition.lang='en-AU';return true;},start(onResult,onEnd){if(!this.recognition&&!this.init()){onEnd&&onEnd('');return;}this.active=true;this.recognition.onresult=e=>{onResult(e.results[0][0].transcript);};this.recognition.onend=()=>{this.active=false;onEnd&&onEnd();};this.recognition.onerror=()=>{this.active=false;onEnd&&onEnd('');};try{this.recognition.start();}catch(e){}},stop(){this.active=false;try{this.recognition&&this.recognition.stop();}catch(e){}}};
const Sophie={childName:'Milla',childAge:6,subject:'general',systemPrompt(){return `You are Miss Sophie, a warm fun encouraging teacher for ${this.childName} who is ${this.childAge} years old teaching ${this.subject}. Always use their name. Keep replies to 1-2 short sentences. Be enthusiastic. If they tell a joke laugh warmly. Never use markdown.`;},async ask(msg,ctx=''){const prompt=ctx?`Context: ${ctx}\nChild said: "${msg}"`:msg;try{const res=await fetch(SOPHIE_CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','x-api-key':SOPHIE_CONFIG.apiKey,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:SOPHIE_CONFIG.model,max_tokens:120,system:this.systemPrompt(),messages:[{role:'user',content:prompt}]})});const data=await res.json();return data?.content?.[0]?.text||`Great effort ${this.childName}!`;}catch(e){return `Great effort ${this.childName}! Keep going!`;}},praise(n){const p=[`Great job ${n}!`,`You are amazing ${n}!`,`Woohoo! That is right ${n}!`,`Brilliant work ${n}!`,`Yes! You got it ${n}! I am so proud of you!`,`Super star ${n}!`];return p[Math.floor(Math.random()*p.length)];},encourage(n){const p=[`Almost ${n}! Have another try!`,`Oops! That is okay ${n}, let us try again!`,`Not quite ${n}! You are getting closer!`,`Keep going ${n}, you are doing great!`];return p[Math.floor(Math.random()*p.length)];}};
function launchConfetti(count=40){const colors=['#FF6EB4','#9B59B6','#FFD700','#74B9FF','#55EFC4'];for(let i=0;i<count;i++){const el=document.createElement('div');el.className='confetti-piece';el.style.left=Math.random()*100+'vw';el.style.background=colors[Math.floor(Math.random()*colors.length)];el.style.animationDuration=(1.5+Math.random()*2)+'s';el.style.animationDelay=(Math.random()*.8)+'s';document.body.appendChild(el);el.addEventListener('animationend',()=>el.remove());}}
function initStars(count=18){const wrap=document.querySelector('.stars');if(!wrap)return;for(let i=0;i<count;i++){const s=document.createElement('div');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=(Math.random()*3)+'s';s.style.animationDuration=(2+Math.random()*2)+'s';s.style.width=s.style.height=(6+Math.random()*10)+'px';wrap.appendChild(s);}}
function getCurrentChild(){return sessionStorage.getItem('sophie_child')||'Milla';}
function getCurrentAge(){return parseInt(sessionStorage.getItem('sophie_age')||'6');}
function setCurrentChild(name,age=6){sessionStorage.setItem('sophie_child',name);sessionStorage.setItem('sophie_age',age);Sophie.childName=name;Sophie.childAge=age;}
function updateScoreDisplay(){const child=getCurrentChild();const data=Progress.getChild(child);const el=document.getElementById('stars-count');if(el)el.textContent=data.stars;}
